<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>netpaw-svc</AssemblyName>
    <RootNamespace>NetPaw.ServiceHost</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <ApplicationIcon>../NetPaw.Tray/netpaw.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile Condition="'$(SelfContained)' == 'true'">true</EnableCompressionInSingleFile>
    <SelfContained>false</SelfContained>
    <UserSecretsId></UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NetPaw.Core/NetPaw.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.12" />
  </ItemGroup>
</Project>
