<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>NetPaw</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Presets\presets.json" LogicalName="presets.json" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
</Project>
