#!/usr/bin/env python3
"""readme-verify — generated by pawkit readmecheck; proves the README's checkable claims.
Regenerate after README changes: `pawkit readmecheck extract --write` (needs the router) or edit
.claude/readme-claims.json by hand and run `pawkit readmecheck genscript`. Exit 1 on any failure."""
import fnmatch, glob as _glob, json, os, re, shlex, subprocess, sys

CLAIMS = [
 {
  "line": 23,
  "text": "**Tiny and fast** \u2014 two executables, ~1.5 MB together, no installer, no service, no telemetry.",
  "kind": "size",
  "check": {
   "pattern": "out/netpaw-win-x64.zip",
   "max_mb": 2.0
  },
  "id": "c1"
 },
 {
  "line": 93,
  "text": "| `netpaw-win-x64-standalone.zip` | nothing | ~85 MB (tray 49 MB + CLI 38 MB, compressed single files) |",
  "kind": "size",
  "check": {
   "pattern": "out/netpaw-win-x64-standalone.zip",
   "max_mb": 100.0
  },
  "id": "c2"
 },
 {
  "line": 94,
  "text": "| `NetPaw-<version>.msi` | [.NET 10 Desktop Runtime](https://dotnet.microsoft.com/download/dotnet/10.0) | ~1 MB, per-machine, for Intune/GPO |",
  "kind": "file",
  "check": {
   "path": "deploy/msi/Package.wxs"
  },
  "id": "c3"
 },
 {
  "line": 47,
  "text": "MIT licensed. Windows 10/11, .NET 10.",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Tray/NetPaw.Tray.csproj",
   "regex": "net10\\.0-windows",
   "min": 1,
   "max": 1
  },
  "id": "c4"
 },
 {
  "line": 44,
  "text": "**Enterprise-ready** \u2014 MSI for Intune/GPO, read-only managed profiles from `%ProgramData%`, registry policy with ADMX (pin the adapter/hotkey, deny reach/DHCP/user profiles). See [docs/ENTERPRISE.md](docs/ENTERPRISE.md).",
  "kind": "file",
  "check": {
   "path": "docs/ENTERPRISE.md"
  },
  "id": "c5"
 },
 {
  "line": 45,
  "text": "**Online profile packs** \u2014 subscribe to signed `index.json` repositories (the community pack in this repo, or your company's). Fetched only when you click *Sync*, cached, never auto-applied. See [docs/PACK-FORMAT.md](docs/PACK-FORMAT.md).",
  "kind": "file",
  "check": {
   "path": "docs/PACK-FORMAT.md"
  },
  "id": "c6"
 },
 {
  "line": 194,
  "text": "MIT \u2014 see [LICENSE](LICENSE).",
  "kind": "file",
  "check": {
   "path": "LICENSE"
  },
  "id": "c7"
 },
 {
  "line": 75,
  "text": "[![CI](https://github.com/smol-kitten/netpaw/actions/workflows/ci.yml/badge.svg)](https://github.com/smol-kitten/netpaw/actions/workflows/ci.yml) ![C#](https://img.shields.io/badge/C%23-239120?style=for-the-badge&logo=csharp&logoColor=white) ![License](https://img.shields.io/badge/license-MIT-blue?style=for-the-badge)",
  "kind": "url",
  "check": {
   "url": "https://github.com/smol-kitten/netpaw/actions/workflows/ci.yml"
  },
  "id": "c8"
 },
 {
  "line": 92,
  "text": "| `netpaw-win-x64.zip` | [.NET 10 Desktop Runtime](https://dotnet.microsoft.com/download/dotnet/10.0) | ~1.5 MB |",
  "kind": "url",
  "check": {
   "url": "https://dotnet.microsoft.com/download/dotnet/10.0"
  },
  "id": "c9"
 },
 {
  "line": 88,
  "text": "Grab a zip from [Releases](../../releases):",
  "kind": "url",
  "check": {
   "url": "https://github.com/smol-kitten/netpaw/releases"
  },
  "id": "c10"
 },
 {
  "line": 15,
  "text": "- **Device presets** \u2014 factory default addresses of ~60 common routers, switches, firewalls,",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Presets/presets.json",
   "regex": "\"vendor\"",
   "min": 50,
   "max": 100
  },
  "id": "c11"
 },
 {
  "line": 15,
  "text": "- **Device presets** \u2014 factory default addresses of ~60 common routers, switches, firewalls,",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Presets/presets.json",
   "regex": "\"ip\"",
   "min": 50,
   "max": 100
  },
  "id": "c12"
 },
 {
  "line": 15,
  "text": "- **Device presets** \u2014 factory default addresses of ~60 common routers, switches, firewalls,",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Presets/presets.json",
   "regex": "\"model\"",
   "min": 50,
   "max": 100
  },
  "id": "c13"
 },
 {
  "line": 31,
  "text": "- **Auto-switch** (opt-in per profile) \u2014 learn a network's fingerprint (gateway MAC, subnet, DHCP server, DNS suffix, ARP neighbours, plus the LLDP/CDP switch port and Wi-Fi BSSID when known \u2014 weighted, so a shared VRRP MAC or a common subnet alone never triggers); on link-up NetPaw applies the profile that scores best by a clear margin. Asks once, undo in the menu, never on ambiguity.",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Scan/AutoSwitcher.cs",
   "regex": "VRRP|BSSID|LLDP|CDP|gateway MAC|subnet|DHCP server|DNS suffix|ARP neighbours",
   "min": 1
  },
  "id": "c14"
 },
 {
  "line": 32,
  "text": "- **Update check** (opt-in \u2014 asked once on first start; one GitHub API call a day, never downloads) \u2014 a balloon once per newer release; click opens the release page. *Settings \u2192 Updates* or policy `AllowUpdateCheck=0` turns it off.",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Updates/UpdateChecker.cs",
   "regex": "AllowUpdateCheck|GitHub|API|balloon|release",
   "min": 1
  },
  "id": "c15"
 },
 {
  "line": 33,
  "text": "- **Main window** (optional) \u2014 Overview \u00b7 Profiles \u00b7 Tools \u00b7 Map \u00b7 Log in one resizable dark window; tray menu, double-click, `--main`, or make the tray click open it. The tray, hotkeys and quick panel stay as they are.",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Tray/MainForm.cs",
   "regex": "Overview|Profiles|Tools|Map|Log|resizable|dark",
   "min": 1
  },
  "id": "c16"
 },
 {
  "line": 34,
  "text": "- **Intent watcher** \u2014 \"msedge cannot reach 192.168.88.1:80 \u2014 no reply for 4 s. Profile *MikroTik lab* covers it\" with a one-click *Reach*. Reads the local TCP table every 2 s (one call, nothing sent), tells host-silent from nobody-beyond-the-gateway, never acts by itself.",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Connectivity/IntentWatcher.cs",
   "regex": "TCP table|2 s|host-silent|nobody-beyond-the-gateway|Reach",
   "min": 1
  },
  "id": "c17"
 },
 {
  "line": 35,
  "text": "- **Quiet by default** \u2014 every info-card row has a mode (*never / on issue / always*), so a healthy network shows five lines and a dock, Wi-Fi, VPN or switch row appears only when it has something to say. Errors always show. Auto-pin uses the same modes.",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Model/Settings.cs",
   "regex": "Never|OnIssue|Always|AutoPin",
   "min": 1,
   "max": 1000000000
  },
  "id": "c18"
 },
 {
  "line": 36,
  "text": "- **Self-watching** \u2014 the check loop backs off on a stable network (30 \u2192 120 s), returns to the fast rate on any change, cancels a hung round after twice the interval, and tells you when its last result is stale. Every background task is guarded: a failure is logged with its name (and, in the telemetry build, reported with the last 40 log lines and the network state).",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Connectivity/Connectivity.cs",
   "regex": "30|120|stale|40 log lines|network state",
   "min": 1
  },
  "id": "c19"
 }
]

def _read(p, n=200000):
    try:
        return open(p, encoding="utf-8", errors="replace").read(n)
    except Exception:
        return ""

# ---------------------------------------------------------------- verification (deterministic)
def _files(root, pattern):
    return [p for p in _glob.glob(os.path.join(root, pattern), recursive=True) if os.path.isfile(p)]


def run_claim(root, c, online=True):
    k, ch = c["kind"], c["check"]
    try:
        if k == "file":
            return os.path.exists(os.path.join(root, ch["path"])), f"{ch['path']} {'exists' if os.path.exists(os.path.join(root, ch['path'])) else 'missing'}"
        if k == "glob":
            n = len(_files(root, ch["pattern"]))
            lo, hi = int(ch.get("min", 0)), int(ch.get("max", 10**9))
            return lo <= n <= hi, f"{n} file(s) match {ch['pattern']} (want {lo}..{hi})"
        if k == "size":
            fs = _files(root, ch["pattern"])
            mb = sum(os.path.getsize(p) for p in fs) / 1048576
            if not fs:
                return None, f"no files match {ch['pattern']} (build first?)"
            ok = (mb <= float(ch["max_mb"])) if "max_mb" in ch else (mb >= float(ch["min_mb"]))
            return ok, f"{mb:.2f} MB across {len(fs)} file(s) (limit {ch.get('max_mb') or ch.get('min_mb')} MB)"
        if k == "cmd":
            r = subprocess.run(shlex.split(ch["cmd"]), cwd=root, capture_output=True, text=True, timeout=60)
            out = (r.stdout or "") + (r.stderr or "")
            ok = (r.returncode == int(ch.get("expect_rc", 0))) and (re.search(ch["regex"], out) is not None if ch.get("regex") else True)
            return ok, f"rc={r.returncode}" + (f", regex {'matched' if re.search(ch['regex'], out) else 'missing'}" if ch.get("regex") else "")
        if k == "grep":
            gp = os.path.join(root, ch["path"])
            if os.path.isdir(gp):          # "157 tests" lives across a test PROJECT, not one file
                t = "".join(_read(os.path.join(dp, f), 400000) for dp, dn, fn in os.walk(gp) for f in fn
                            if f.endswith((".cs", ".py", ".js", ".ts", ".go", ".rs", ".php", ".java", ".kt", ".md", ".txt", ".json", ".yml", ".yaml", ".toml", ".xml", ".csproj")))
            else:
                t = _read(gp)
            if not t:
                return None, f"{ch['path']} unreadable"
            n = len(re.findall(ch["regex"], t, re.M))
            lo, hi = int(ch.get("min", 1)), int(ch.get("max", 10**9))
            return lo <= n <= hi, f"{n} match(es) of /{ch['regex']}/ in {ch['path']} (want {lo}..{hi})"
        if k == "version":
            a = re.search(ch["regex"], _read(os.path.join(root, ch["path"])), re.M)
            b = re.search(ch["source_regex"], _read(os.path.join(root, ch["source"])), re.M)
            va, vb = (a.group(1) if a and a.groups() else (a.group(0) if a else None)), (b.group(1) if b and b.groups() else (b.group(0) if b else None))
            return (va is not None and va == vb), f"{ch['path']}={va} vs {ch['source']}={vb}"
        if k == "url":
            if not online:
                return None, "offline"
            import urllib.request
            req = urllib.request.Request(ch["url"], method="HEAD", headers={"User-Agent": "readmecheck/1"})
            try:
                code = urllib.request.urlopen(req, timeout=15).status
            except Exception as e:
                code = getattr(e, "code", 0)
            return (0 < code < 400), f"HTTP {code}"
    except Exception as e:
        return None, f"error: {str(e)[:120]}"
    return None, "unknown kind"




def main():
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    online = os.environ.get("README_VERIFY_OFFLINE", "") == ""
    bad = 0
    for c in CLAIMS:
        ok, d = run_claim(root, c, online)
        tag = "PASS" if ok else ("SKIP" if ok is None else "FAIL")
        bad += tag == "FAIL"
        print(f"[{tag}] {c['id']} L{c.get('line')} {c['kind']}: {c.get('text')} -> {d}")
    print(f"{len(CLAIMS)} claim(s), {bad} failing")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
