#!/usr/bin/env python3
"""readme-verify — generated by pawkit readmecheck; proves the README's checkable claims.
Regenerate after README changes: `pawkit readmecheck extract --write` (needs the router) or edit
.claude/readme-claims.json by hand and run `pawkit readmecheck genscript`. Exit 1 on any failure."""
import fnmatch, glob as _glob, json, os, re, shlex, subprocess, sys

CLAIMS = [
 {
  "line": 212,
  "text": "MIT \u2014 see [LICENSE](LICENSE).",
  "kind": "file",
  "check": {
   "path": "LICENSE"
  },
  "id": "c1"
 },
 {
  "line": 5,
  "text": "[![CI](https://github.com/smol-kitten/netpaw/actions/workflows/ci.yml/badge.svg)](https://github.com/smol-kitten/netpaw/actions/workflows/ci.yml) ![C#](https://img.shields.io/badge/C%23-239120?style=for-the-badge&logo=csharp&logoColor=white) ![License](https://img.shields.io/badge/license-MIT-blue?style=for-the-badge)",
  "kind": "url",
  "check": {
   "url": "https://github.com/smol-kitten/netpaw/actions/workflows/ci.yml"
  },
  "id": "c2"
 },
 {
  "line": 12,
  "text": "Free (MIT) \u00b7 Windows 10/11 \u00b7 .NET 10 \u00b7 every change is a plain `netsh` command you can preview.",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Tray/NetPaw.Tray.csproj",
   "regex": "net10\\.0-windows",
   "min": 1,
   "max": 1
  },
  "id": "c3"
 },
 {
  "line": 74,
  "text": "| `NetPaw-<version>.msi` | most people; Intune/GPO | [.NET 10 Desktop Runtime](https://dotnet.microsoft.com/download/dotnet/10.0) | ~1 MB, per-machine |",
  "kind": "file",
  "check": {
   "path": "deploy/msi/Package.wxs"
  },
  "id": "c4"
 },
 {
  "line": 75,
  "text": "| `netpaw-win-x64.zip` | portable | .NET 10 Desktop Runtime | ~1.5 MB |",
  "kind": "size",
  "check": {
   "pattern": "out/netpaw-win-x64.zip",
   "max_mb": 2.0
  },
  "id": "c5"
 },
 {
  "line": 76,
  "text": "| `netpaw-win-x64-standalone.zip` | portable, no .NET installed | nothing | ~85 MB |",
  "kind": "size",
  "check": {
   "pattern": "out/netpaw-win-x64-standalone.zip",
   "max_mb": 100.0
  },
  "id": "c6"
 },
 {
  "line": 77,
  "text": "| `NetPaw-<version>-telemetry.msi` | opt-in crash reports and usage counts ([TELEMETRY.md](docs/TELEMETRY.md)) | .NET 10 Desktop Runtime | ~1 MB |",
  "kind": "file",
  "check": {
   "path": "deploy/msi/Package.wxs"
  },
  "id": "c7"
 },
 {
  "line": 84,
  "text": "> **Signed from v0.13.1.** Each release has `SIGNATURES.md` and `r0.crt`.",
  "kind": "version",
  "check": {
   "path": "docs/signed-release.md",
   "regex": "v0\\.13\\.1",
   "source": "README.md",
   "source_regex": "v0\\.13\\.1"
  },
  "id": "c8"
 },
 {
  "line": 86,
  "text": "> [docs/signed-release.md](docs/signed-release.md).",
  "kind": "file",
  "check": {
   "path": "docs/signed-release.md"
  },
  "id": "c9"
 },
 {
  "line": 107,
  "text": "**[docs/usage.md](docs/usage.md)**.",
  "kind": "file",
  "check": {
   "path": "docs/usage.md"
  },
  "id": "c10"
 },
 {
  "line": 115,
  "text": "- `profiles.json` \u2014 your profiles. Hand-editable, git-able, copy to the next laptop.",
  "kind": "file",
  "check": {
   "path": "src/NetPaw.Core/Model/Profile.cs"
  },
  "id": "c11"
 },
 {
  "line": 116,
  "text": "- `presets.json` \u2014 your own device presets (same schema as the bundled list).",
  "kind": "file",
  "check": {
   "path": "src/NetPaw.Core/Presets/presets.json"
  },
  "id": "c12"
 },
 {
  "line": 117,
  "text": "- `settings.json`, `state.json` (temporary addresses), `netpaw.log`, `cache\\` (synced packs).",
  "kind": "file",
  "check": {
   "path": "src/NetPaw.Core/Model/Settings.cs"
  },
  "id": "c13"
 },
 {
  "line": 118,
  "text": "- `%ProgramData%\\NetPaw\\profiles.d\\*.json` \u2014 managed profiles from your organisation (read-only).",
  "kind": "glob",
  "check": {
   "pattern": "deploy/gpo/NetPaw.admx",
   "min": 1,
   "max": 1
  },
  "id": "c14"
 },
 {
  "line": 119,
  "text": "- `HKLM\\SOFTWARE\\Policies\\NetPaw` \u2014 machine policy ([docs/ENTERPRISE.md](docs/ENTERPRISE.md)).",
  "kind": "file",
  "check": {
   "path": "docs/ENTERPRISE.md"
  },
  "id": "c15"
 },
 {
  "line": 178,
  "text": "- `src/NetPaw.Core` \u2014 models, IP math, planner, reach resolver, presets, policy, repos, update check.",
  "kind": "file",
  "check": {
   "path": "src/NetPaw.Core/NetPaw.Core.csproj"
  },
  "id": "c16"
 },
 {
  "line": 180,
  "text": "- `src/NetPaw.Tray` \u2014 WinForms, dark, no designer files.",
  "kind": "file",
  "check": {
   "path": "src/NetPaw.Tray/NetPaw.Tray.csproj"
  },
  "id": "c17"
 },
 {
  "line": 182,
  "text": "- `deploy/` \u2014 MSI, ADMX, Intune scripts, public signing certificates.",
  "kind": "glob",
  "check": {
   "pattern": "deploy/**/*",
   "min": 1,
   "max": 100
  },
  "id": "c18"
 },
 {
  "line": 199,
  "text": "| [features.md](docs/features.md) | every feature in detail |",
  "kind": "file",
  "check": {
   "path": "docs/features.md"
  },
  "id": "c19"
 },
 {
  "line": 202,
  "text": "| [PACK-FORMAT.md](docs/PACK-FORMAT.md) | online profile packs |",
  "kind": "file",
  "check": {
   "path": "docs/PACK-FORMAT.md"
  },
  "id": "c20"
 },
 {
  "line": 203,
  "text": "| [TELEMETRY.md](docs/TELEMETRY.md) | what the `-telemetry` build sends |",
  "kind": "file",
  "check": {
   "path": "docs/TELEMETRY.md"
  },
  "id": "c21"
 },
 {
  "line": 74,
  "text": "| `NetPaw-<version>.msi` | most people; Intune/GPO | [.NET 10 Desktop Runtime](https://dotnet.microsoft.com/download/dotnet/10.0) | ~1 MB, per-machine |",
  "kind": "url",
  "check": {
   "url": "https://dotnet.microsoft.com/download/dotnet/10.0"
  },
  "id": "c22"
 },
 {
  "line": 70,
  "text": "Download from [Releases](../../releases):",
  "kind": "url",
  "check": {
   "url": "https://github.com/smol-kitten/netpaw/releases"
  },
  "id": "c23"
 },
 {
  "line": 26,
  "text": "| **Switch networks** | Profiles per adapter (several IPs, gateway, DNS, routes, VLAN) \u00b7 DHCP in one click \u00b7 **reach mode**: type an IP and NetPaw gets you onto its subnet \u00b7 ~60 device presets \u00b7 hotkeys \u00b7 auto-switch on known networks \u00b7 scan for a working profile \u00b7 verify after every apply |",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Presets/presets.json",
   "regex": "\"vendor\"",
   "min": 50,
   "max": 100
  },
  "id": "c24"
 },
 {
  "line": 26,
  "text": "| **Switch networks** | Profiles per adapter (several IPs, gateway, DNS, routes, VLAN) \u00b7 DHCP in one click \u00b7 **reach mode**: type an IP and NetPaw gets you onto its subnet \u00b7 ~60 device presets \u00b7 hotkeys \u00b7 auto-switch on known networks \u00b7 scan for a working profile \u00b7 verify after every apply |",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Presets/presets.json",
   "regex": "\"ip\"",
   "min": 50,
   "max": 100
  },
  "id": "c25"
 },
 {
  "line": 26,
  "text": "| **Switch networks** | Profiles per adapter (several IPs, gateway, DNS, routes, VLAN) \u00b7 DHCP in one click \u00b7 **reach mode**: type an IP and NetPaw gets you onto its subnet \u00b7 ~60 device presets \u00b7 hotkeys \u00b7 auto-switch on known networks \u00b7 scan for a working profile \u00b7 verify after every apply |",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Presets/presets.json",
   "regex": "\"model\"",
   "min": 50,
   "max": 100
  },
  "id": "c26"
 },
 {
  "line": 26,
  "text": "| **Switch networks** | Profiles per adapter (several IPs, gateway, DNS, routes, VLAN) \u00b7 DHCP in one click \u00b7 **reach mode**: type an IP and NetPaw gets you onto its subnet \u00b7 ~60 device presets \u00b7 hotkeys \u00b7 auto-switch on known networks \u00b7 scan for a working profile \u00b7 verify after every apply |",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Scan/AutoSwitcher.cs",
   "regex": "VRRP|BSSID|LLDP|CDP|gateway MAC|subnet|DHCP server|DNS suffix|ARP neighbours",
   "min": 1
  },
  "id": "c27"
 },
 {
  "line": 31,
  "text": "| **Updates** | Signed releases \u00b7 opt-in update check that installs only a verified, signed MSI |",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Updates/UpdateChecker.cs",
   "regex": "AllowUpdateCheck|GitHub|API|balloon|release",
   "min": 1
  },
  "id": "c28"
 },
 {
  "line": 180,
  "text": "- `src/NetPaw.Tray` \u2014 WinForms, dark, no designer files.",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Tray/MainForm.cs",
   "regex": "Overview|Profiles|Tools|Map|Log|resizable|dark",
   "min": 1
  },
  "id": "c29"
 },
 {
  "line": 27,
  "text": "| **See what is wrong** | Info card (`Ctrl+Alt+I`) with link/gateway/DNS/internet \u2713/\u2717 \u00b7 plain-language advice \u00b7 monitor mode \u00b7 \"the browser cannot reach X\" watcher \u00b7 VPN status \u00b7 incident log |",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Connectivity/IntentWatcher.cs",
   "regex": "TCP table|2 s|host-silent|nobody-beyond-the-gateway|Reach",
   "min": 1
  },
  "id": "c30"
 },
 {
  "line": 27,
  "text": "| **See what is wrong** | Info card (`Ctrl+Alt+I`) with link/gateway/DNS/internet \u2713/\u2717 \u00b7 plain-language advice \u00b7 monitor mode \u00b7 \"the browser cannot reach X\" watcher \u00b7 VPN status \u00b7 incident log |",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Model/Settings.cs",
   "regex": "Never|OnIssue|Always|AutoPin",
   "min": 1,
   "max": 1000000000
  },
  "id": "c31"
 },
 {
  "line": 27,
  "text": "| **See what is wrong** | Info card (`Ctrl+Alt+I`) with link/gateway/DNS/internet \u2713/\u2717 \u00b7 plain-language advice \u00b7 monitor mode \u00b7 \"the browser cannot reach X\" watcher \u00b7 VPN status \u00b7 incident log |",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Connectivity/Connectivity.cs",
   "regex": "30|120|stale|40 log lines|network state",
   "min": 1
  },
  "id": "c32"
 },
 {
  "line": 79,
  "text": "Only the `-telemetry` MSI contains telemetry code.",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Core/Telemetry/TelemetryClient.cs",
   "regex": "telemetry",
   "min": 1
  },
  "id": "c33"
 },
 {
  "line": 84,
  "text": "> **Signed from v0.13.1.** Each release has `SIGNATURES.md` and `r0.crt`. Windows still shows \"unknown",
  "kind": "file",
  "check": {
   "path": "deploy/pki/r0.crt"
  },
  "id": "c34"
 },
 {
  "line": 84,
  "text": "> **Signed from v0.13.1.** Each release has `SIGNATURES.md` and `r0.crt`. Windows still shows \"unknown",
  "kind": "grep",
  "check": {
   "path": ".github/workflows/ci.yml",
   "regex": "r0\\.crt",
   "min": 1
  },
  "id": "c35"
 },
 {
  "line": 31,
  "text": "| **Updates** | Signed releases \u00b7 opt-in update check that installs only a verified, signed MSI |",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Tray/TrayApp.cs",
   "regex": "NOT verified",
   "min": 1
  },
  "id": "c36"
 },
 {
  "line": 82,
  "text": "*Settings \u2192 start with Windows* adds an elevated scheduled task, so there is no UAC prompt at logon.",
  "kind": "grep",
  "check": {
   "path": "src/NetPaw.Tray/SettingsForm.cs",
   "regex": "start with Windows|scheduled task|elevated",
   "min": 1
  },
  "id": "c37"
 },
 {
  "line": 182,
  "text": "- `deploy/` \u2014 MSI, ADMX, Intune scripts, public signing certificates.",
  "kind": "file",
  "check": {
   "path": "deploy/gpo/NetPaw.admx"
  },
  "id": "c38"
 },
 {
  "line": 182,
  "text": "- `deploy/` \u2014 MSI, ADMX, Intune scripts, public signing certificates.",
  "kind": "file",
  "check": {
   "path": "deploy/intune/Deploy-NetPawProfiles.ps1"
  },
  "id": "c39"
 },
 {
  "line": 183,
  "text": "- `packs/` \u2014 online profile packs (not built in).",
  "kind": "file",
  "check": {
   "path": "packs/community/index.json"
  },
  "id": "c40"
 },
 {
  "line": 185,
  "text": "CI builds, signs and verifies on Linux. The MSI is built and install-tested on a hosted Windows runner.",
  "kind": "grep",
  "check": {
   "path": ".github/workflows/ci.yml",
   "regex": "runs-on: n4",
   "min": 1
  },
  "id": "c41"
 },
 {
  "line": 185,
  "text": "CI builds, signs and verifies on Linux. The MSI is built and install-tested on a hosted Windows runner.",
  "kind": "grep",
  "check": {
   "path": ".github/workflows/ci.yml",
   "regex": "runs-on: windows-latest",
   "min": 1
  },
  "id": "c42"
 }
]

def _read(p, n=200000):
    try:
        return open(p, encoding="utf-8", errors="replace").read(n)
    except Exception:
        return ""

# ---------------------------------------------------------------- verification (deterministic)
def _files(root, pattern):
    return [p for p in _glob.glob(os.path.join(root, pattern), recursive=True) if os.path.isfile(p)]


def run_claim(root, c, online=True):
    k, ch = c["kind"], c["check"]
    try:
        if k == "file":
            return os.path.exists(os.path.join(root, ch["path"])), f"{ch['path']} {'exists' if os.path.exists(os.path.join(root, ch['path'])) else 'missing'}"
        if k == "glob":
            n = len(_files(root, ch["pattern"]))
            lo, hi = int(ch.get("min", 0)), int(ch.get("max", 10**9))
            return lo <= n <= hi, f"{n} file(s) match {ch['pattern']} (want {lo}..{hi})"
        if k == "size":
            fs = _files(root, ch["pattern"])
            mb = sum(os.path.getsize(p) for p in fs) / 1048576
            if not fs:
                return None, f"no files match {ch['pattern']} (build first?)"
            ok = (mb <= float(ch["max_mb"])) if "max_mb" in ch else (mb >= float(ch["min_mb"]))
            return ok, f"{mb:.2f} MB across {len(fs)} file(s) (limit {ch.get('max_mb') or ch.get('min_mb')} MB)"
        if k == "cmd":
            r = subprocess.run(shlex.split(ch["cmd"]), cwd=root, capture_output=True, text=True, timeout=60)
            out = (r.stdout or "") + (r.stderr or "")
            ok = (r.returncode == int(ch.get("expect_rc", 0))) and (re.search(ch["regex"], out) is not None if ch.get("regex") else True)
            return ok, f"rc={r.returncode}" + (f", regex {'matched' if re.search(ch['regex'], out) else 'missing'}" if ch.get("regex") else "")
        if k == "grep":
            gp = os.path.join(root, ch["path"])
            if os.path.isdir(gp):          # "157 tests" lives across a test PROJECT, not one file
                t = "".join(_read(os.path.join(dp, f), 400000) for dp, dn, fn in os.walk(gp) for f in fn
                            if f.endswith((".cs", ".py", ".js", ".ts", ".go", ".rs", ".php", ".java", ".kt", ".md", ".txt", ".json", ".yml", ".yaml", ".toml", ".xml", ".csproj")))
            else:
                t = _read(gp)
            if not t:
                return None, f"{ch['path']} unreadable"
            n = len(re.findall(ch["regex"], t, re.M))
            lo, hi = int(ch.get("min", 1)), int(ch.get("max", 10**9))
            return lo <= n <= hi, f"{n} match(es) of /{ch['regex']}/ in {ch['path']} (want {lo}..{hi})"
        if k == "version":
            a = re.search(ch["regex"], _read(os.path.join(root, ch["path"])), re.M)
            b = re.search(ch["source_regex"], _read(os.path.join(root, ch["source"])), re.M)
            va, vb = (a.group(1) if a and a.groups() else (a.group(0) if a else None)), (b.group(1) if b and b.groups() else (b.group(0) if b else None))
            return (va is not None and va == vb), f"{ch['path']}={va} vs {ch['source']}={vb}"
        if k == "url":
            if not online:
                return None, "offline"
            import urllib.request
            req = urllib.request.Request(ch["url"], method="HEAD", headers={"User-Agent": "readmecheck/1"})
            try:
                code = urllib.request.urlopen(req, timeout=15).status
            except Exception as e:
                code = getattr(e, "code", 0)
            return (0 < code < 400), f"HTTP {code}"
    except Exception as e:
        return None, f"error: {str(e)[:120]}"
    return None, "unknown kind"




def main():
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    online = os.environ.get("README_VERIFY_OFFLINE", "") == ""
    bad = 0
    for c in CLAIMS:
        ok, d = run_claim(root, c, online)
        tag = "PASS" if ok else ("SKIP" if ok is None else "FAIL")
        bad += tag == "FAIL"
        print(f"[{tag}] {c['id']} L{c.get('line')} {c['kind']}: {c.get('text')} -> {d}")
    print(f"{len(CLAIMS)} claim(s), {bad} failing")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
